# Generated by Django 2.1.2 on 2018-10-05 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservationId', models.IntegerField(primary_key=True, serialize=False)),
                ('number_of_customers', models.IntegerField()),
                ('reserved_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('deposit', models.FloatField()),
                ('status', models.CharField(max_length=50)),
                ('fee', models.FloatField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant')),
            ],
        ),
    ]
