# Generated by Django 2.1.2 on 2018-10-07 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20181006_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='reservationId',
            new_name='reservation_id',
        ),
    ]
